# 需迁移至nacos的配置
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      #          lower-case-service-id: false
      default-filters: #全局熔断器
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
      routes:
        - id: msc-service-provider
          uri: lb://msc-service-provider # 负载均衡地址
          #          uri: http://localhost:9000/ #直接指定URL
          predicates:
            - Path=/sp/**
          filters:
            - StripPrefix=1 #将/sp前缀去掉
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}' #用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
                redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率。
                redis-rate-limiter.burstCapacity: 3  #令牌桶总容量。
        - id: msc-service-consumer
          uri: lb://msc-service-consumer
          predicates:
            - Path=/sc/**
          filters:
            - StripPrefix=1
        - id: itsa
          uri: lb://itsa
          predicates:
            - Path=/itsa/**

  redis:
    host: 192.168.136.10
    port: 6379
    database: 0
    password: 123456

# 自定义服务列表
itsa:
  ribbon:
    listOfServers: http://localhost:9000/，http://localhost:9001/

#hystrix:
#  shareSecurityContext: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000